---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

    I had small knowledge coming into the class as an Economics major I've had to use R in several courses with emphasis on packages such as dplyr and ggplot. However I never really knew the fundamentals of each package nor fully understood what each function is doing, rather it was just off of memorization and referencing old code. In this course we used dplyr a lot which I learned comes in a even better equip package for data science tidyverse. Key skills I learned as a student of data science include tactics of data manipulation, how to visualize you results, cleaning and creating tidy data. I knew I have grown as a coder because I still recall looking at code intimadated prior to this course but now I feel I have key knowledge on objects, arguments, functions and am able to logically understand or even create an educated guess of the objective of the code if looking at new packages. Best of all I know were to get help in R about checking syntax functions which is an extremely helpful tool that I picked up.

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

I would have to say that the areas that I made the most growth in this course were also when I was the most confused or challenged. I can remember Lab 4 took me extensive time and even after put in even more time into my revisions. I am really proud of the faceted plot in Lab 4 Q6, this plot alone took me hours across multiple days. I experienced growth with this specific plot because of the need for small attention of detail; these small factors translate to create a big difference in a viewers understand which is possibly the number one goal as a practicing data scientist. I constantly had to ask myself what more could I do to make this visualization clear and reader friendly. I explored and practiced small changes in scaling, breaks, theme metrics such as legend position, key sizing, axis text sizing, aspect ratios and adjusting the order of the legend to stay consistent with the colors on the graph.
